[project]
name = "the-gemma-4-developer-agent-competition"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "DeianHsu", email = "663781679@qq.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
the-gemma-4-developer-agent-competition = "the_gemma_4_developer_agent_competition:main"

[build-system]
requires = ["uv_build>=0.12.24,<0.13.0"]
build-backend = "uv_build"
